version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
        - "8000:80"
    env_file:
      - .env
    restart: always
    networks:
      - network

    

networks:
  network:
    driver: bridge
    
  

    # ports:
    #   - "443:433"