version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirement/nginx
    ports:
        - "443:443"
    env_file:
      - .env
    restart: always
    networks:
      - network

    

networks:
  network:
    driver: bridge
